version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.3.0
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Configurar SSH
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "SHA256:SsIaTHn3fn6gZjNvpvSxK/sfdVP5xbGt0XsOj/spVJY"

      - run:
          name: Clonar Repositórios Adicionais
          command: |
            cd ..
            git clone https://github.com/Lucaslgbr/fastapi-auth.git
            git clone https://github.com/Lucaslgbr/spreadsheet-importer.git
            git clone https://github.com/andrecristen/notification-service.git
            git clone https://github.com/andrecristen/planilha-frontend.git
            cd -

      - run:
          name: Instalar Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
      - run:
          name: Create Docker Network (services)
          command: docker network create services
            
      - run:
          name: Create Docker Network (rabbitmq-network)
          command: docker network create rabbitmq-network
          
      - run:
          name: Verificar variáveis de ambiente
          command: printenv

      - run:
          name: Verificar Instalação do Docker Compose
          command: docker-compose --version

      - run:
          name: Instalar Dependências do Docusaurus
          command: |
            cd website
            npm install

      - run:
          name: Build do Site do Docusaurus
          command: |
            cd website
            npm run build

      - run:
          name: Deploy do Site do Docusaurus
          command: |
            cd website
            git config --global user.email "andrecristenibirama@gmail.com"
            git config --global user.name "andrecristen"
            GIT_USER=andrecristen GITHUB_TOKEN=${GITHUB_TOKEN} npx docusaurus deploy --skip-build --ci --verbose --github-token ${GITHUB_TOKEN}

      - run:
          name: Iniciar Serviços com Docker Compose
          command: docker-compose up --build

      - run:
          name: Executar Testes
          command: docker-compose run all-services npm test

      - run:
          name: Parar e Remover Serviços
          command: docker-compose down

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
