version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Configurar SSH
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "SHA256:SsIaTHn3fn6gZjNvpvSxK/sfdVP5xbGt0XsOj/spVJY"

      - run:
          name: Clonar Repositórios Adicionais
          command: |
            git clone https://github.com/Lucaslgbr/fastapi-auth.git
            git clone https://github.com/Lucaslgbr/spreadsheet-importer.git
            git clone https://github.com/andrecristen/notification-service.git
            git clone https://github.com/andrecristen/planilha-frontend.git

      - run:
          name: Listar Diretórios
          command: ls -R

      - run:
          name: Criar Redes Docker
          command: |
            docker network create services
            docker network create rabbitmq-network

       - run:
          name: Construir a Imagem Docker
          command: |
            docker build -t all-services .
          when: always

      - run:
          name: Exibir Imagens Docker
          command: docker images

      - run:
          name: Executar Testes na Imagem Docker
          command: |
            docker run  all-services npm test

      - run:
          name: Remover Redes Docker
          command: |
            docker network rm services
            docker network rm rabbitmq-network

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
