version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout 

      - run:
          name: Configurar SSH
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "SHA256:SsIaTHn3fn6gZjNvpvSxK/sfdVP5xbGt0XsOj/spVJY"

      - run:
          name: Clonar Repositórios Adicionais
          command: |
            git clone https://github.com/Lucaslgbr/fastapi-auth.git
            git clone https://github.com/Lucaslgbr/spreadsheet-importer.git
            git clone https://github.com/andrecristen/notification-service.git
            git clone https://github.com/andrecristen/planilha-frontend.git

      - run:
          name: Instalar Dependências
          command: |
            cd fastapi-auth && pip install -r requirements.txt && cd ..
            cd spreadsheet-importer && pip install -r requirements.txt && cd ..
            cd notification-service && npm install && cd ..
            cd planilha-frontend && npm install && cd ..
            cd all-services

      - run:
          name: Executar Testes
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
