version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Configurar SSH
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "SHA256:SsIaTHn3fn6gZjNvpvSxK/sfdVP5xbGt0XsOj/spVJY"

      - run:
          name: Clonar Repositórios Adicionais
          command: |
            git clone https://github.com/Lucaslgbr/fastapi-auth.git
            git clone https://github.com/Lucaslgbr/spreadsheet-importer.git
            git clone https://github.com/andrecristen/notification-service.git
            git clone https://github.com/andrecristen/planilha-frontend.git

      - run:
          name: Listar Diretórios
          command: ls -R

      - run:
          name: Instalar Python e pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip

      - run:
          name: Instalar Dependências - fastapi-auth
          command: |
            cd fastapi-auth
            pip3 install -r requirements.txt
            cd ..

      - run:
          name: Instalar Dependências - spreadsheet-importer
          command: |
            cd spreadsheet-importer
            pip3 install -r requirements.txt
            cd ..

      - run:
          name: Instalar Dependências - notification-service
          command: |
            cd notification-service
            npm install
            cd ..

      - run:
          name: Instalar Dependências - planilha-frontend
          command: |
            cd planilha-frontend
            npm install
            cd ..

      - run:
          name: Executar Testes
          command: |
            cd all-services
            npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build