global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'fastapi-auth-up-all'
    scrape_interval: 5s
    static_configs:
      - targets: ['fastapi-auth-up-all:8000']
      
  - job_name: 'spreadsheet-importer-up-all'
    scrape_interval: 5s
    static_configs:
      - targets: ['spreadsheet-importer-up-all:8001']
      