name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./website

      - name: Build Docusaurus site
        run: npm run build
        working-directory: ./website

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "andrecristenibirama@gmail.com"
          git config --global user.name "andrecristen"
          npm install -g gh-pages
          cd website/build
          git init
          git add .
          git commit -m "Deploy website"
          git push --force "https://x-access-token:${{ secrets.GH_PAT }}@github.com/andrecristen/all-services.git" master:gh-pages